# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.group_Satellites = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_Satellites.sizePolicy().hasHeightForWidth())
        self.group_Satellites.setSizePolicy(sizePolicy)
        self.group_Satellites.setObjectName("group_Satellites")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.group_Satellites)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.group_SatCalc = QtWidgets.QGroupBox(self.group_Satellites)
        self.group_SatCalc.setObjectName("group_SatCalc")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.group_SatCalc)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabs_Calculator = QtWidgets.QTabWidget(self.group_SatCalc)
        self.tabs_Calculator.setObjectName("tabs_Calculator")
        self.tab_TLEs = QtWidgets.QWidget()
        self.tab_TLEs.setObjectName("tab_TLEs")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_TLEs)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.button_LoadFile = QtWidgets.QPushButton(self.tab_TLEs)
        self.button_LoadFile.setObjectName("button_LoadFile")
        self.gridLayout_11.addWidget(self.button_LoadFile, 0, 2, 1, 1)
        self.label_Filename = QtWidgets.QLabel(self.tab_TLEs)
        self.label_Filename.setObjectName("label_Filename")
        self.gridLayout_11.addWidget(self.label_Filename, 0, 0, 1, 1)
        self.value_Filename = QtWidgets.QLineEdit(self.tab_TLEs)
        self.value_Filename.setObjectName("value_Filename")
        self.gridLayout_11.addWidget(self.value_Filename, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 0, 3, 1, 1)
        self.label_Search = QtWidgets.QLabel(self.tab_TLEs)
        self.label_Search.setObjectName("label_Search")
        self.gridLayout_11.addWidget(self.label_Search, 1, 0, 1, 1)
        self.value_Search = QtWidgets.QLineEdit(self.tab_TLEs)
        self.value_Search.setObjectName("value_Search")
        self.gridLayout_11.addWidget(self.value_Search, 1, 1, 1, 1)
        self.button_Search = QtWidgets.QPushButton(self.tab_TLEs)
        self.button_Search.setObjectName("button_Search")
        self.gridLayout_11.addWidget(self.button_Search, 1, 2, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.table_TLEs = QtWidgets.QTableWidget(self.tab_TLEs)
        self.table_TLEs.setObjectName("table_TLEs")
        self.table_TLEs.setColumnCount(3)
        self.table_TLEs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_TLEs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_TLEs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_TLEs.setHorizontalHeaderItem(2, item)
        self.gridLayout_15.addWidget(self.table_TLEs, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.tabs_Calculator.addTab(self.tab_TLEs, "")
        self.tab_Passes = QtWidgets.QWidget()
        self.tab_Passes.setObjectName("tab_Passes")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_Passes)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.table_Passes = QtWidgets.QTableWidget(self.tab_Passes)
        self.table_Passes.setObjectName("table_Passes")
        self.table_Passes.setColumnCount(4)
        self.table_Passes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Passes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Passes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Passes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Passes.setHorizontalHeaderItem(3, item)
        self.gridLayout_13.addWidget(self.table_Passes, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.box_Site = QtWidgets.QGroupBox(self.tab_Passes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_Site.sizePolicy().hasHeightForWidth())
        self.box_Site.setSizePolicy(sizePolicy)
        self.box_Site.setObjectName("box_Site")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.box_Site)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Lat = QtWidgets.QLabel(self.box_Site)
        self.label_Lat.setObjectName("label_Lat")
        self.gridLayout_4.addWidget(self.label_Lat, 0, 0, 1, 1)
        self.value_Lat = QtWidgets.QLineEdit(self.box_Site)
        self.value_Lat.setObjectName("value_Lat")
        self.gridLayout_4.addWidget(self.value_Lat, 0, 1, 1, 1)
        self.label_Lon = QtWidgets.QLabel(self.box_Site)
        self.label_Lon.setObjectName("label_Lon")
        self.gridLayout_4.addWidget(self.label_Lon, 1, 0, 1, 1)
        self.value_Lon = QtWidgets.QLineEdit(self.box_Site)
        self.value_Lon.setObjectName("value_Lon")
        self.gridLayout_4.addWidget(self.value_Lon, 1, 1, 1, 1)
        self.label_Height = QtWidgets.QLabel(self.box_Site)
        self.label_Height.setObjectName("label_Height")
        self.gridLayout_4.addWidget(self.label_Height, 2, 0, 1, 1)
        self.value_Height = QtWidgets.QLineEdit(self.box_Site)
        self.value_Height.setObjectName("value_Height")
        self.gridLayout_4.addWidget(self.value_Height, 2, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.box_Site)
        self.box_Time = QtWidgets.QGroupBox(self.tab_Passes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_Time.sizePolicy().hasHeightForWidth())
        self.box_Time.setSizePolicy(sizePolicy)
        self.box_Time.setObjectName("box_Time")
        self.gridLayout = QtWidgets.QGridLayout(self.box_Time)
        self.gridLayout.setObjectName("gridLayout")
        self.date_Start = QtWidgets.QDateTimeEdit(self.box_Time)
        self.date_Start.setObjectName("date_Start")
        self.gridLayout.addWidget(self.date_Start, 0, 1, 1, 1)
        self.label_StartTime = QtWidgets.QLabel(self.box_Time)
        self.label_StartTime.setObjectName("label_StartTime")
        self.gridLayout.addWidget(self.label_StartTime, 0, 0, 1, 1)
        self.date_Stop = QtWidgets.QDateTimeEdit(self.box_Time)
        self.date_Stop.setObjectName("date_Stop")
        self.gridLayout.addWidget(self.date_Stop, 1, 1, 1, 1)
        self.label_StopTime = QtWidgets.QLabel(self.box_Time)
        self.label_StopTime.setObjectName("label_StopTime")
        self.gridLayout.addWidget(self.label_StopTime, 1, 0, 1, 1)
        self.label_Resolution = QtWidgets.QLabel(self.box_Time)
        self.label_Resolution.setObjectName("label_Resolution")
        self.gridLayout.addWidget(self.label_Resolution, 2, 0, 1, 1)
        self.value_Resolution = QtWidgets.QDoubleSpinBox(self.box_Time)
        self.value_Resolution.setObjectName("value_Resolution")
        self.gridLayout.addWidget(self.value_Resolution, 2, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.box_Time)
        self.box_Process = QtWidgets.QGroupBox(self.tab_Passes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_Process.sizePolicy().hasHeightForWidth())
        self.box_Process.setSizePolicy(sizePolicy)
        self.box_Process.setObjectName("box_Process")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.box_Process)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.button_Process = QtWidgets.QPushButton(self.box_Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Process.sizePolicy().hasHeightForWidth())
        self.button_Process.setSizePolicy(sizePolicy)
        self.button_Process.setObjectName("button_Process")
        self.gridLayout_10.addWidget(self.button_Process, 3, 0, 1, 1)
        self.label_Status = QtWidgets.QLabel(self.box_Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Status.sizePolicy().hasHeightForWidth())
        self.label_Status.setSizePolicy(sizePolicy)
        self.label_Status.setObjectName("label_Status")
        self.gridLayout_10.addWidget(self.label_Status, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Degrees = QtWidgets.QLabel(self.box_Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Degrees.sizePolicy().hasHeightForWidth())
        self.label_Degrees.setSizePolicy(sizePolicy)
        self.label_Degrees.setObjectName("label_Degrees")
        self.horizontalLayout_4.addWidget(self.label_Degrees)
        self.value_Degrees = QtWidgets.QDoubleSpinBox(self.box_Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_Degrees.sizePolicy().hasHeightForWidth())
        self.value_Degrees.setSizePolicy(sizePolicy)
        self.value_Degrees.setObjectName("value_Degrees")
        self.horizontalLayout_4.addWidget(self.value_Degrees)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.box_Process)
        self.gridLayout_13.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_Passes)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 2, 0, 1, 1)
        self.tabs_Calculator.addTab(self.tab_Passes, "")
        self.tab_Graph = QtWidgets.QWidget()
        self.tab_Graph.setObjectName("tab_Graph")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_Graph)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.layout_Graph = QtWidgets.QGridLayout()
        self.layout_Graph.setObjectName("layout_Graph")
        self.gridLayout_14.addLayout(self.layout_Graph, 0, 0, 1, 1)
        self.tabs_Calculator.addTab(self.tab_Graph, "")
        self.gridLayout_7.addWidget(self.tabs_Calculator, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.group_SatCalc, 0, 0, 1, 1)
        self.group_SatQueue = QtWidgets.QGroupBox(self.group_Satellites)
        self.group_SatQueue.setObjectName("group_SatQueue")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.group_SatQueue)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_Waiting = QtWidgets.QTableWidget(self.group_SatQueue)
        self.table_Waiting.setObjectName("table_Waiting")
        self.table_Waiting.setColumnCount(3)
        self.table_Waiting.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Waiting.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Waiting.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Waiting.setHorizontalHeaderItem(2, item)
        self.gridLayout_3.addWidget(self.table_Waiting, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.group_SatQueue)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.group_SatQueue, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.group_Satellites, 0, 1, 1, 1)
        self.box_Telescope = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_Telescope.sizePolicy().hasHeightForWidth())
        self.box_Telescope.setSizePolicy(sizePolicy)
        self.box_Telescope.setObjectName("box_Telescope")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.box_Telescope)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.box_MountSite = QtWidgets.QGroupBox(self.box_Telescope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_MountSite.sizePolicy().hasHeightForWidth())
        self.box_MountSite.setSizePolicy(sizePolicy)
        self.box_MountSite.setObjectName("box_MountSite")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.box_MountSite)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_ip = QtWidgets.QLabel(self.box_MountSite)
        self.label_ip.setObjectName("label_ip")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ip)
        self.button_Connect = QtWidgets.QPushButton(self.box_MountSite)
        self.button_Connect.setObjectName("button_Connect")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.button_Connect)
        self.value_Connected = QtWidgets.QLabel(self.box_MountSite)
        self.value_Connected.setObjectName("value_Connected")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_Connected)
        self.label_Geometry = QtWidgets.QLabel(self.box_MountSite)
        self.label_Geometry.setObjectName("label_Geometry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Geometry)
        self.value_Geometry = QtWidgets.QLabel(self.box_MountSite)
        self.value_Geometry.setObjectName("value_Geometry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_Geometry)
        self.label_MoveStatus = QtWidgets.QLabel(self.box_MountSite)
        self.label_MoveStatus.setObjectName("label_MoveStatus")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_MoveStatus)
        self.value_MoveStatus = QtWidgets.QLabel(self.box_MountSite)
        self.value_MoveStatus.setObjectName("value_MoveStatus")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_MoveStatus)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.value_ip = QtWidgets.QLineEdit(self.box_MountSite)
        self.value_ip.setObjectName("value_ip")
        self.horizontalLayout.addWidget(self.value_ip)
        self.value_port = QtWidgets.QLineEdit(self.box_MountSite)
        self.value_port.setObjectName("value_port")
        self.horizontalLayout.addWidget(self.value_port)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.gridLayout_12.addLayout(self.formLayout, 0, 1, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_telescope_lat = QtWidgets.QLabel(self.box_MountSite)
        self.label_telescope_lat.setObjectName("label_telescope_lat")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_telescope_lat)
        self.value_telescope_lat = QtWidgets.QLineEdit(self.box_MountSite)
        self.value_telescope_lat.setReadOnly(True)
        self.value_telescope_lat.setObjectName("value_telescope_lat")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_telescope_lat)
        self.label_telescope_lon = QtWidgets.QLabel(self.box_MountSite)
        self.label_telescope_lon.setObjectName("label_telescope_lon")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_telescope_lon)
        self.value_telescope_lon = QtWidgets.QLineEdit(self.box_MountSite)
        self.value_telescope_lon.setReadOnly(True)
        self.value_telescope_lon.setObjectName("value_telescope_lon")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_telescope_lon)
        self.label_telescope_height = QtWidgets.QLabel(self.box_MountSite)
        self.label_telescope_height.setObjectName("label_telescope_height")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_telescope_height)
        self.value_telescope_height = QtWidgets.QLineEdit(self.box_MountSite)
        self.value_telescope_height.setReadOnly(True)
        self.value_telescope_height.setObjectName("value_telescope_height")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_telescope_height)
        self.value_lst = QtWidgets.QLineEdit(self.box_MountSite)
        self.value_lst.setReadOnly(True)
        self.value_lst.setObjectName("value_lst")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_lst)
        self.label_lst = QtWidgets.QLabel(self.box_MountSite)
        self.label_lst.setObjectName("label_lst")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_lst)
        self.label = QtWidgets.QLabel(self.box_MountSite)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.box_MountSite)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.gridLayout_12.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.box_MountSite, 0, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.box_MountStatus = QtWidgets.QGroupBox(self.box_Telescope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_MountStatus.sizePolicy().hasHeightForWidth())
        self.box_MountStatus.setSizePolicy(sizePolicy)
        self.box_MountStatus.setObjectName("box_MountStatus")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.box_MountStatus)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_ra = QtWidgets.QLabel(self.box_MountStatus)
        self.label_ra.setObjectName("label_ra")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ra)
        self.value_ra = QtWidgets.QLineEdit(self.box_MountStatus)
        self.value_ra.setReadOnly(True)
        self.value_ra.setObjectName("value_ra")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_ra)
        self.label_dec = QtWidgets.QLabel(self.box_MountStatus)
        self.label_dec.setObjectName("label_dec")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_dec)
        self.value_dec = QtWidgets.QLineEdit(self.box_MountStatus)
        self.value_dec.setReadOnly(True)
        self.value_dec.setObjectName("value_dec")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_dec)
        self.label_alt = QtWidgets.QLabel(self.box_MountStatus)
        self.label_alt.setObjectName("label_alt")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_alt)
        self.value_alt = QtWidgets.QLineEdit(self.box_MountStatus)
        self.value_alt.setReadOnly(True)
        self.value_alt.setObjectName("value_alt")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_alt)
        self.label_az = QtWidgets.QLabel(self.box_MountStatus)
        self.label_az.setObjectName("label_az")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_az)
        self.value_az = QtWidgets.QLineEdit(self.box_MountStatus)
        self.value_az.setReadOnly(True)
        self.value_az.setObjectName("value_az")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_az)
        self.gridLayout_16.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.box_MountStatus, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.box_Telescope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_a0_enabled = QtWidgets.QLabel(self.groupBox)
        self.label_a0_enabled.setObjectName("label_a0_enabled")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_a0_enabled)
        self.value_a0_enabled = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_enabled.setReadOnly(True)
        self.value_a0_enabled.setObjectName("value_a0_enabled")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_a0_enabled)
        self.label_a0_rms = QtWidgets.QLabel(self.groupBox)
        self.label_a0_rms.setObjectName("label_a0_rms")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_a0_rms)
        self.value_a0_rms = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_rms.setReadOnly(True)
        self.value_a0_rms.setObjectName("value_a0_rms")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_a0_rms)
        self.label_a0_dist = QtWidgets.QLabel(self.groupBox)
        self.label_a0_dist.setObjectName("label_a0_dist")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_a0_dist)
        self.value_a0_dist = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_dist.setReadOnly(True)
        self.value_a0_dist.setObjectName("value_a0_dist")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_a0_dist)
        self.label_a0_servo = QtWidgets.QLabel(self.groupBox)
        self.label_a0_servo.setObjectName("label_a0_servo")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_a0_servo)
        self.value_a0_servo = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_servo.setReadOnly(True)
        self.value_a0_servo.setObjectName("value_a0_servo")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_a0_servo)
        self.label_a0_position = QtWidgets.QLabel(self.groupBox)
        self.label_a0_position.setObjectName("label_a0_position")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_a0_position)
        self.value_a0_position = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_position.setReadOnly(True)
        self.value_a0_position.setObjectName("value_a0_position")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.value_a0_position)
        self.gridLayout_2.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.box_Telescope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_a1_enabled = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_enabled.setObjectName("label_a1_enabled")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_a1_enabled)
        self.value_a1_enabled = QtWidgets.QLineEdit(self.groupBox_2)
        self.value_a1_enabled.setReadOnly(True)
        self.value_a1_enabled.setObjectName("value_a1_enabled")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_a1_enabled)
        self.label_a1_rms = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_rms.setObjectName("label_a1_rms")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_a1_rms)
        self.value_a1_rms = QtWidgets.QLineEdit(self.groupBox_2)
        self.value_a1_rms.setReadOnly(True)
        self.value_a1_rms.setObjectName("value_a1_rms")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_a1_rms)
        self.label_a1_dist = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_dist.setObjectName("label_a1_dist")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_a1_dist)
        self.value_a1_dist = QtWidgets.QLineEdit(self.groupBox_2)
        self.value_a1_dist.setReadOnly(True)
        self.value_a1_dist.setObjectName("value_a1_dist")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_a1_dist)
        self.label_a1_servo = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_servo.setObjectName("label_a1_servo")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_a1_servo)
        self.value_a1_servo = QtWidgets.QLineEdit(self.groupBox_2)
        self.value_a1_servo.setReadOnly(True)
        self.value_a1_servo.setObjectName("value_a1_servo")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_a1_servo)
        self.label_a1_position = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_position.setObjectName("label_a1_position")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_a1_position)
        self.label_a1_position_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.label_a1_position_2.setReadOnly(True)
        self.label_a1_position_2.setObjectName("label_a1_position_2")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_a1_position_2)
        self.gridLayout_17.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.box_Telescope)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.button_Test = QtWidgets.QPushButton(self.groupBox_3)
        self.button_Test.setObjectName("button_Test")
        self.gridLayout_19.addWidget(self.button_Test, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.box_Telescope, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs_Calculator.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_Satellites.setTitle(_translate("MainWindow", "Satellites"))
        self.group_SatCalc.setTitle(_translate("MainWindow", "Pass Calculator"))
        self.button_LoadFile.setText(_translate("MainWindow", "Load File"))
        self.label_Filename.setText(_translate("MainWindow", "TLEs File name:"))
        self.label_Search.setText(_translate("MainWindow", "Search names:"))
        self.button_Search.setText(_translate("MainWindow", "Filter"))
        item = self.table_TLEs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Line 1"))
        item = self.table_TLEs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Line 2"))
        item = self.table_TLEs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Line 3"))
        self.tabs_Calculator.setTabText(self.tabs_Calculator.indexOf(self.tab_TLEs), _translate("MainWindow", "TLE List"))
        item = self.table_Passes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Satellite Name"))
        item = self.table_Passes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Max altitude"))
        item = self.table_Passes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time of max alt"))
        item = self.table_Passes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Az at max alt"))
        self.box_Site.setTitle(_translate("MainWindow", "Observation Co-ordinates"))
        self.label_Lat.setText(_translate("MainWindow", "Lat"))
        self.label_Lon.setText(_translate("MainWindow", "Lon"))
        self.label_Height.setText(_translate("MainWindow", "Height"))
        self.box_Time.setTitle(_translate("MainWindow", "Search parameters"))
        self.label_StartTime.setText(_translate("MainWindow", "Start Time"))
        self.label_StopTime.setText(_translate("MainWindow", "Stop Time"))
        self.label_Resolution.setText(_translate("MainWindow", "Resolution (mins)"))
        self.box_Process.setTitle(_translate("MainWindow", "Processing"))
        self.button_Process.setText(_translate("MainWindow", "Find Passes"))
        self.label_Status.setText(_translate("MainWindow", "Status: Inactive"))
        self.label_Degrees.setText(_translate("MainWindow", "Filter Alt (°)"))
        self.label_2.setText(_translate("MainWindow", "Double click passes in this list to add to the tracking queue. The telescope will track the pass when it starts."))
        self.tabs_Calculator.setTabText(self.tabs_Calculator.indexOf(self.tab_Passes), _translate("MainWindow", "Passes"))
        self.tabs_Calculator.setTabText(self.tabs_Calculator.indexOf(self.tab_Graph), _translate("MainWindow", "Graph"))
        self.group_SatQueue.setTitle(_translate("MainWindow", "Queue"))
        item = self.table_Waiting.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Satelite Name"))
        item = self.table_Waiting.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Track Start"))
        item = self.table_Waiting.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Track End"))
        self.label_3.setText(_translate("MainWindow", "Double click waiting list items to remove them from the waiting list (and cancel the tracking request)."))
        self.box_Telescope.setTitle(_translate("MainWindow", "Telescope Mount Status"))
        self.box_MountSite.setTitle(_translate("MainWindow", "Site"))
        self.label_ip.setText(_translate("MainWindow", "Mount control IP"))
        self.button_Connect.setText(_translate("MainWindow", "Connect to mount"))
        self.value_Connected.setText(_translate("MainWindow", "Not connected."))
        self.label_Geometry.setText(_translate("MainWindow", "Mount geometry:"))
        self.value_Geometry.setText(_translate("MainWindow", "something"))
        self.label_MoveStatus.setText(_translate("MainWindow", "Move status:"))
        self.value_MoveStatus.setText(_translate("MainWindow", "Not moving"))
        self.label_telescope_lat.setText(_translate("MainWindow", "Latitude"))
        self.label_telescope_lon.setText(_translate("MainWindow", "Longitude"))
        self.label_telescope_height.setText(_translate("MainWindow", "Height"))
        self.label_lst.setText(_translate("MainWindow", "LST"))
        self.label.setText(_translate("MainWindow", "LST->Time"))
        self.box_MountStatus.setTitle(_translate("MainWindow", "Pointing"))
        self.label_ra.setText(_translate("MainWindow", "RA"))
        self.label_dec.setText(_translate("MainWindow", "Dec"))
        self.label_alt.setText(_translate("MainWindow", "Alt"))
        self.label_az.setText(_translate("MainWindow", "Az"))
        self.groupBox.setTitle(_translate("MainWindow", "Axis 0"))
        self.label_a0_enabled.setText(_translate("MainWindow", "Enabled?"))
        self.label_a0_rms.setText(_translate("MainWindow", "RMS error"))
        self.label_a0_dist.setText(_translate("MainWindow", "dist. to target"))
        self.label_a0_servo.setText(_translate("MainWindow", "servo error"))
        self.label_a0_position.setText(_translate("MainWindow", "position"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Axis 1"))
        self.label_a1_enabled.setText(_translate("MainWindow", "Enabled?"))
        self.label_a1_rms.setText(_translate("MainWindow", "RMS error"))
        self.label_a1_dist.setText(_translate("MainWindow", "dist. to target"))
        self.label_a1_servo.setText(_translate("MainWindow", "servo error"))
        self.label_a1_position.setText(_translate("MainWindow", "position"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Accesories placeholder (or maybe telescope control buttons?"))
        self.button_Test.setText(_translate("MainWindow", "The button"))

