# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1281, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.group_Telescope = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_Telescope.sizePolicy().hasHeightForWidth())
        self.group_Telescope.setSizePolicy(sizePolicy)
        self.group_Telescope.setObjectName("group_Telescope")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.group_Telescope)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_2 = QtWidgets.QGroupBox(self.group_Telescope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_a1_enabled = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_enabled.setObjectName("label_a1_enabled")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_a1_enabled)
        self.value_a1_enabled = QtWidgets.QLineEdit(self.groupBox_2)
        self.value_a1_enabled.setReadOnly(True)
        self.value_a1_enabled.setObjectName("value_a1_enabled")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_a1_enabled)
        self.label_a1_rms = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_rms.setObjectName("label_a1_rms")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_a1_rms)
        self.value_a1_rms = QtWidgets.QLineEdit(self.groupBox_2)
        self.value_a1_rms.setReadOnly(True)
        self.value_a1_rms.setObjectName("value_a1_rms")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_a1_rms)
        self.label_a1_dist = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_dist.setObjectName("label_a1_dist")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_a1_dist)
        self.value_a1_dist = QtWidgets.QLineEdit(self.groupBox_2)
        self.value_a1_dist.setReadOnly(True)
        self.value_a1_dist.setObjectName("value_a1_dist")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_a1_dist)
        self.label_a1_servo = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_servo.setObjectName("label_a1_servo")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_a1_servo)
        self.value_a1_servo = QtWidgets.QLineEdit(self.groupBox_2)
        self.value_a1_servo.setReadOnly(True)
        self.value_a1_servo.setObjectName("value_a1_servo")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_a1_servo)
        self.label_a1_position = QtWidgets.QLabel(self.groupBox_2)
        self.label_a1_position.setObjectName("label_a1_position")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_a1_position)
        self.value_a1_position = QtWidgets.QLineEdit(self.groupBox_2)
        self.value_a1_position.setReadOnly(True)
        self.value_a1_position.setObjectName("value_a1_position")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.value_a1_position)
        self.gridLayout_17.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.box_MountStatus = QtWidgets.QGroupBox(self.group_Telescope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_MountStatus.sizePolicy().hasHeightForWidth())
        self.box_MountStatus.setSizePolicy(sizePolicy)
        self.box_MountStatus.setObjectName("box_MountStatus")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.box_MountStatus)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.value_dec_status = QtWidgets.QLineEdit(self.box_MountStatus)
        self.value_dec_status.setReadOnly(True)
        self.value_dec_status.setObjectName("value_dec_status")
        self.gridLayout_29.addWidget(self.value_dec_status, 3, 1, 1, 1)
        self.label_alt_status = QtWidgets.QLabel(self.box_MountStatus)
        self.label_alt_status.setObjectName("label_alt_status")
        self.gridLayout_29.addWidget(self.label_alt_status, 0, 0, 1, 1)
        self.value_az_status = QtWidgets.QLineEdit(self.box_MountStatus)
        self.value_az_status.setReadOnly(True)
        self.value_az_status.setObjectName("value_az_status")
        self.gridLayout_29.addWidget(self.value_az_status, 1, 1, 1, 1)
        self.label_ra_status = QtWidgets.QLabel(self.box_MountStatus)
        self.label_ra_status.setObjectName("label_ra_status")
        self.gridLayout_29.addWidget(self.label_ra_status, 2, 0, 1, 1)
        self.label_az_status = QtWidgets.QLabel(self.box_MountStatus)
        self.label_az_status.setObjectName("label_az_status")
        self.gridLayout_29.addWidget(self.label_az_status, 1, 0, 1, 1)
        self.label_dec_status = QtWidgets.QLabel(self.box_MountStatus)
        self.label_dec_status.setObjectName("label_dec_status")
        self.gridLayout_29.addWidget(self.label_dec_status, 3, 0, 1, 1)
        self.value_alt_status = QtWidgets.QLineEdit(self.box_MountStatus)
        self.value_alt_status.setReadOnly(True)
        self.value_alt_status.setObjectName("value_alt_status")
        self.gridLayout_29.addWidget(self.value_alt_status, 0, 1, 1, 1)
        self.value_ra_status = QtWidgets.QLineEdit(self.box_MountStatus)
        self.value_ra_status.setReadOnly(True)
        self.value_ra_status.setObjectName("value_ra_status")
        self.gridLayout_29.addWidget(self.value_ra_status, 2, 1, 1, 1)
        self.option_j2000_status = QtWidgets.QCheckBox(self.box_MountStatus)
        self.option_j2000_status.setObjectName("option_j2000_status")
        self.gridLayout_29.addWidget(self.option_j2000_status, 4, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.box_MountStatus, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.group_Telescope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_a0_enabled = QtWidgets.QLabel(self.groupBox)
        self.label_a0_enabled.setObjectName("label_a0_enabled")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_a0_enabled)
        self.value_a0_enabled = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_enabled.setReadOnly(True)
        self.value_a0_enabled.setObjectName("value_a0_enabled")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_a0_enabled)
        self.label_a0_rms = QtWidgets.QLabel(self.groupBox)
        self.label_a0_rms.setObjectName("label_a0_rms")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_a0_rms)
        self.value_a0_rms = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_rms.setReadOnly(True)
        self.value_a0_rms.setObjectName("value_a0_rms")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_a0_rms)
        self.label_a0_dist = QtWidgets.QLabel(self.groupBox)
        self.label_a0_dist.setObjectName("label_a0_dist")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_a0_dist)
        self.value_a0_dist = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_dist.setReadOnly(True)
        self.value_a0_dist.setObjectName("value_a0_dist")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_a0_dist)
        self.label_a0_servo = QtWidgets.QLabel(self.groupBox)
        self.label_a0_servo.setObjectName("label_a0_servo")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_a0_servo)
        self.value_a0_servo = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_servo.setReadOnly(True)
        self.value_a0_servo.setObjectName("value_a0_servo")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_a0_servo)
        self.label_a0_position = QtWidgets.QLabel(self.groupBox)
        self.label_a0_position.setObjectName("label_a0_position")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_a0_position)
        self.value_a0_position = QtWidgets.QLineEdit(self.groupBox)
        self.value_a0_position.setReadOnly(True)
        self.value_a0_position.setObjectName("value_a0_position")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.value_a0_position)
        self.gridLayout_2.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox, 0, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        self.box_MountSite = QtWidgets.QGroupBox(self.group_Telescope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_MountSite.sizePolicy().hasHeightForWidth())
        self.box_MountSite.setSizePolicy(sizePolicy)
        self.box_MountSite.setObjectName("box_MountSite")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.box_MountSite)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_telescope_lat = QtWidgets.QLabel(self.box_MountSite)
        self.label_telescope_lat.setObjectName("label_telescope_lat")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_telescope_lat)
        self.value_telescope_lat = QtWidgets.QLineEdit(self.box_MountSite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_telescope_lat.sizePolicy().hasHeightForWidth())
        self.value_telescope_lat.setSizePolicy(sizePolicy)
        self.value_telescope_lat.setMinimumSize(QtCore.QSize(150, 0))
        self.value_telescope_lat.setMaximumSize(QtCore.QSize(150, 16777215))
        self.value_telescope_lat.setReadOnly(True)
        self.value_telescope_lat.setObjectName("value_telescope_lat")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_telescope_lat)
        self.label_telescope_lon = QtWidgets.QLabel(self.box_MountSite)
        self.label_telescope_lon.setObjectName("label_telescope_lon")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_telescope_lon)
        self.value_telescope_lon = QtWidgets.QLineEdit(self.box_MountSite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_telescope_lon.sizePolicy().hasHeightForWidth())
        self.value_telescope_lon.setSizePolicy(sizePolicy)
        self.value_telescope_lon.setMinimumSize(QtCore.QSize(150, 0))
        self.value_telescope_lon.setMaximumSize(QtCore.QSize(150, 16777215))
        self.value_telescope_lon.setReadOnly(True)
        self.value_telescope_lon.setObjectName("value_telescope_lon")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_telescope_lon)
        self.label_telescope_height = QtWidgets.QLabel(self.box_MountSite)
        self.label_telescope_height.setObjectName("label_telescope_height")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_telescope_height)
        self.value_telescope_height = QtWidgets.QLineEdit(self.box_MountSite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_telescope_height.sizePolicy().hasHeightForWidth())
        self.value_telescope_height.setSizePolicy(sizePolicy)
        self.value_telescope_height.setMinimumSize(QtCore.QSize(150, 0))
        self.value_telescope_height.setMaximumSize(QtCore.QSize(150, 16777215))
        self.value_telescope_height.setReadOnly(True)
        self.value_telescope_height.setObjectName("value_telescope_height")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_telescope_height)
        self.label_lst = QtWidgets.QLabel(self.box_MountSite)
        self.label_lst.setObjectName("label_lst")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_lst)
        self.value_lst = QtWidgets.QLineEdit(self.box_MountSite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_lst.sizePolicy().hasHeightForWidth())
        self.value_lst.setSizePolicy(sizePolicy)
        self.value_lst.setMinimumSize(QtCore.QSize(150, 0))
        self.value_lst.setMaximumSize(QtCore.QSize(150, 16777215))
        self.value_lst.setReadOnly(True)
        self.value_lst.setObjectName("value_lst")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_lst)
        self.gridLayout_21.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_ip = QtWidgets.QLabel(self.box_MountSite)
        self.label_ip.setObjectName("label_ip")
        self.gridLayout_12.addWidget(self.label_ip, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.value_ip = QtWidgets.QLineEdit(self.box_MountSite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_ip.sizePolicy().hasHeightForWidth())
        self.value_ip.setSizePolicy(sizePolicy)
        self.value_ip.setMinimumSize(QtCore.QSize(80, 0))
        self.value_ip.setMaximumSize(QtCore.QSize(80, 16777215))
        self.value_ip.setText("")
        self.value_ip.setObjectName("value_ip")
        self.horizontalLayout.addWidget(self.value_ip)
        self.label_port = QtWidgets.QLabel(self.box_MountSite)
        self.label_port.setObjectName("label_port")
        self.horizontalLayout.addWidget(self.label_port)
        self.value_port = QtWidgets.QLineEdit(self.box_MountSite)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_port.sizePolicy().hasHeightForWidth())
        self.value_port.setSizePolicy(sizePolicy)
        self.value_port.setMinimumSize(QtCore.QSize(50, 0))
        self.value_port.setMaximumSize(QtCore.QSize(50, 16777215))
        self.value_port.setObjectName("value_port")
        self.horizontalLayout.addWidget(self.value_port)
        self.option_ip_local = QtWidgets.QCheckBox(self.box_MountSite)
        self.option_ip_local.setChecked(True)
        self.option_ip_local.setObjectName("option_ip_local")
        self.horizontalLayout.addWidget(self.option_ip_local)
        self.gridLayout_12.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_Connect = QtWidgets.QPushButton(self.box_MountSite)
        self.button_Connect.setObjectName("button_Connect")
        self.horizontalLayout_2.addWidget(self.button_Connect)
        self.value_Connected = QtWidgets.QLabel(self.box_MountSite)
        self.value_Connected.setObjectName("value_Connected")
        self.horizontalLayout_2.addWidget(self.value_Connected)
        self.gridLayout_12.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_Geometry = QtWidgets.QLabel(self.box_MountSite)
        self.label_Geometry.setObjectName("label_Geometry")
        self.gridLayout_12.addWidget(self.label_Geometry, 2, 0, 1, 1)
        self.value_Geometry = QtWidgets.QLabel(self.box_MountSite)
        self.value_Geometry.setObjectName("value_Geometry")
        self.gridLayout_12.addWidget(self.value_Geometry, 2, 1, 1, 1)
        self.label_MoveStatus = QtWidgets.QLabel(self.box_MountSite)
        self.label_MoveStatus.setObjectName("label_MoveStatus")
        self.gridLayout_12.addWidget(self.label_MoveStatus, 3, 0, 1, 1)
        self.value_MoveStatus = QtWidgets.QLabel(self.box_MountSite)
        self.value_MoveStatus.setObjectName("value_MoveStatus")
        self.gridLayout_12.addWidget(self.value_MoveStatus, 3, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_12, 0, 1, 1, 1)
        self.gridLayout_20.addWidget(self.box_MountSite, 0, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.group_Telescope)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_3)
        self.tabWidget.setMinimumSize(QtCore.QSize(250, 130))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_goto_altaz = QtWidgets.QWidget()
        self.tab_goto_altaz.setObjectName("tab_goto_altaz")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.tab_goto_altaz)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.lebel_alt_cmd = QtWidgets.QLabel(self.tab_goto_altaz)
        self.lebel_alt_cmd.setObjectName("lebel_alt_cmd")
        self.gridLayout_28.addWidget(self.lebel_alt_cmd, 0, 0, 1, 1)
        self.value_alt_cmd = QtWidgets.QLineEdit(self.tab_goto_altaz)
        self.value_alt_cmd.setReadOnly(False)
        self.value_alt_cmd.setObjectName("value_alt_cmd")
        self.gridLayout_28.addWidget(self.value_alt_cmd, 0, 1, 1, 1)
        self.label_az_cmd = QtWidgets.QLabel(self.tab_goto_altaz)
        self.label_az_cmd.setObjectName("label_az_cmd")
        self.gridLayout_28.addWidget(self.label_az_cmd, 1, 0, 1, 1)
        self.value_az_cmd = QtWidgets.QLineEdit(self.tab_goto_altaz)
        self.value_az_cmd.setReadOnly(False)
        self.value_az_cmd.setObjectName("value_az_cmd")
        self.gridLayout_28.addWidget(self.value_az_cmd, 1, 1, 1, 1)
        self.button_goto_altaz = QtWidgets.QPushButton(self.tab_goto_altaz)
        self.button_goto_altaz.setObjectName("button_goto_altaz")
        self.gridLayout_28.addWidget(self.button_goto_altaz, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_goto_altaz, "")
        self.tab_goto_radec = QtWidgets.QWidget()
        self.tab_goto_radec.setObjectName("tab_goto_radec")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.tab_goto_radec)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_ra_cmd = QtWidgets.QLabel(self.tab_goto_radec)
        self.label_ra_cmd.setObjectName("label_ra_cmd")
        self.gridLayout_30.addWidget(self.label_ra_cmd, 0, 0, 1, 1)
        self.value_ra_cmd = QtWidgets.QLineEdit(self.tab_goto_radec)
        self.value_ra_cmd.setReadOnly(False)
        self.value_ra_cmd.setObjectName("value_ra_cmd")
        self.gridLayout_30.addWidget(self.value_ra_cmd, 0, 1, 1, 1)
        self.label_dec_cmd = QtWidgets.QLabel(self.tab_goto_radec)
        self.label_dec_cmd.setObjectName("label_dec_cmd")
        self.gridLayout_30.addWidget(self.label_dec_cmd, 1, 0, 1, 1)
        self.value_dec_cmd = QtWidgets.QLineEdit(self.tab_goto_radec)
        self.value_dec_cmd.setReadOnly(False)
        self.value_dec_cmd.setObjectName("value_dec_cmd")
        self.gridLayout_30.addWidget(self.value_dec_cmd, 1, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_30)
        self.option_cmd_j2000 = QtWidgets.QCheckBox(self.tab_goto_radec)
        self.option_cmd_j2000.setObjectName("option_cmd_j2000")
        self.horizontalLayout_11.addWidget(self.option_cmd_j2000)
        self.gridLayout_31.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.button_goto_radec = QtWidgets.QPushButton(self.tab_goto_radec)
        self.button_goto_radec.setObjectName("button_goto_radec")
        self.gridLayout_31.addWidget(self.button_goto_radec, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_goto_radec, "")
        self.horizontalLayout_7.addWidget(self.tabWidget)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.button_tle_track = QtWidgets.QPushButton(self.groupBox_4)
        self.button_tle_track.setObjectName("button_tle_track")
        self.gridLayout_27.addWidget(self.button_tle_track, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_tle_cmd = QtWidgets.QLabel(self.groupBox_4)
        self.label_tle_cmd.setObjectName("label_tle_cmd")
        self.horizontalLayout_9.addWidget(self.label_tle_cmd)
        self.value_tle_cmd = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.value_tle_cmd.setMaximumSize(QtCore.QSize(16777215, 75))
        self.value_tle_cmd.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.value_tle_cmd.setPlainText("")
        self.value_tle_cmd.setObjectName("value_tle_cmd")
        self.horizontalLayout_9.addWidget(self.value_tle_cmd)
        self.gridLayout_27.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.value_tle_cmd_start = QtWidgets.QDateTimeEdit(self.groupBox_4)
        self.value_tle_cmd_start.setObjectName("value_tle_cmd_start")
        self.gridLayout_32.addWidget(self.value_tle_cmd_start, 0, 2, 1, 1)
        self.option_tle_cmd_now = QtWidgets.QCheckBox(self.groupBox_4)
        self.option_tle_cmd_now.setChecked(True)
        self.option_tle_cmd_now.setObjectName("option_tle_cmd_now")
        self.gridLayout_32.addWidget(self.option_tle_cmd_now, 0, 1, 1, 1)
        self.label_tle_start = QtWidgets.QLabel(self.groupBox_4)
        self.label_tle_start.setObjectName("label_tle_start")
        self.gridLayout_32.addWidget(self.label_tle_start, 0, 0, 1, 1)
        self.label_tle_stop = QtWidgets.QLabel(self.groupBox_4)
        self.label_tle_stop.setEnabled(False)
        self.label_tle_stop.setObjectName("label_tle_stop")
        self.gridLayout_32.addWidget(self.label_tle_stop, 1, 0, 1, 1)
        self.option_tle_cmd_forever = QtWidgets.QCheckBox(self.groupBox_4)
        self.option_tle_cmd_forever.setEnabled(False)
        self.option_tle_cmd_forever.setObjectName("option_tle_cmd_forever")
        self.gridLayout_32.addWidget(self.option_tle_cmd_forever, 1, 1, 1, 1)
        self.value_tle_cmd_stop = QtWidgets.QDateTimeEdit(self.groupBox_4)
        self.value_tle_cmd_stop.setEnabled(False)
        self.value_tle_cmd_stop.setObjectName("value_tle_cmd_stop")
        self.gridLayout_32.addWidget(self.value_tle_cmd_stop, 1, 2, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_32, 1, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.gridLayout_26.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 45))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.button_cmd_home = QtWidgets.QPushButton(self.groupBox_5)
        self.button_cmd_home.setObjectName("button_cmd_home")
        self.gridLayout_24.addWidget(self.button_cmd_home, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 45))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.button_cmd_stop = QtWidgets.QPushButton(self.groupBox_6)
        self.button_cmd_stop.setObjectName("button_cmd_stop")
        self.gridLayout_23.addWidget(self.button_cmd_stop, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 45))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.button_cmd_park = QtWidgets.QPushButton(self.groupBox_7)
        self.button_cmd_park.setObjectName("button_cmd_park")
        self.gridLayout_22.addWidget(self.button_cmd_park, 0, 0, 1, 1)
        self.option_park_here = QtWidgets.QCheckBox(self.groupBox_7)
        self.option_park_here.setObjectName("option_park_here")
        self.gridLayout_22.addWidget(self.option_park_here, 0, 1, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 45))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.option_tracking = QtWidgets.QCheckBox(self.groupBox_8)
        self.option_tracking.setObjectName("option_tracking")
        self.gridLayout_19.addWidget(self.option_tracking, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_8)
        self.gridLayout_26.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_9.setEnabled(False)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_9.setCheckable(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.value_cmd_raw = QtWidgets.QPlainTextEdit(self.groupBox_9)
        self.value_cmd_raw.setEnabled(False)
        self.value_cmd_raw.setPlainText("")
        self.value_cmd_raw.setObjectName("value_cmd_raw")
        self.gridLayout_25.addWidget(self.value_cmd_raw, 0, 0, 1, 1)
        self.button_cmd_raw = QtWidgets.QPushButton(self.groupBox_9)
        self.button_cmd_raw.setEnabled(False)
        self.button_cmd_raw.setObjectName("button_cmd_raw")
        self.gridLayout_25.addWidget(self.button_cmd_raw, 0, 1, 1, 1)
        self.gridLayout_26.addWidget(self.groupBox_9, 2, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.gridLayout_9.addWidget(self.group_Telescope, 0, 0, 1, 1)
        self.group_Satellites = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_Satellites.sizePolicy().hasHeightForWidth())
        self.group_Satellites.setSizePolicy(sizePolicy)
        self.group_Satellites.setObjectName("group_Satellites")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.group_Satellites)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.group_SatCalc = QtWidgets.QGroupBox(self.group_Satellites)
        self.group_SatCalc.setObjectName("group_SatCalc")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.group_SatCalc)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabs_Calculator = QtWidgets.QTabWidget(self.group_SatCalc)
        self.tabs_Calculator.setObjectName("tabs_Calculator")
        self.tab_TLEs = QtWidgets.QWidget()
        self.tab_TLEs.setObjectName("tab_TLEs")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_TLEs)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.button_LoadFile = QtWidgets.QPushButton(self.tab_TLEs)
        self.button_LoadFile.setObjectName("button_LoadFile")
        self.gridLayout_11.addWidget(self.button_LoadFile, 0, 2, 1, 1)
        self.label_Filename = QtWidgets.QLabel(self.tab_TLEs)
        self.label_Filename.setObjectName("label_Filename")
        self.gridLayout_11.addWidget(self.label_Filename, 0, 0, 1, 1)
        self.value_Filename = QtWidgets.QLineEdit(self.tab_TLEs)
        self.value_Filename.setObjectName("value_Filename")
        self.gridLayout_11.addWidget(self.value_Filename, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 0, 3, 1, 1)
        self.label_Search = QtWidgets.QLabel(self.tab_TLEs)
        self.label_Search.setObjectName("label_Search")
        self.gridLayout_11.addWidget(self.label_Search, 1, 0, 1, 1)
        self.value_Search = QtWidgets.QLineEdit(self.tab_TLEs)
        self.value_Search.setObjectName("value_Search")
        self.gridLayout_11.addWidget(self.value_Search, 1, 1, 1, 1)
        self.button_Search = QtWidgets.QPushButton(self.tab_TLEs)
        self.button_Search.setObjectName("button_Search")
        self.gridLayout_11.addWidget(self.button_Search, 1, 2, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.table_TLEs = QtWidgets.QTableWidget(self.tab_TLEs)
        self.table_TLEs.setObjectName("table_TLEs")
        self.table_TLEs.setColumnCount(3)
        self.table_TLEs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_TLEs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_TLEs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_TLEs.setHorizontalHeaderItem(2, item)
        self.gridLayout_15.addWidget(self.table_TLEs, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_TLEs)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.tabs_Calculator.addTab(self.tab_TLEs, "")
        self.tab_Passes = QtWidgets.QWidget()
        self.tab_Passes.setObjectName("tab_Passes")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_Passes)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.table_Passes = QtWidgets.QTableWidget(self.tab_Passes)
        self.table_Passes.setObjectName("table_Passes")
        self.table_Passes.setColumnCount(4)
        self.table_Passes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Passes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Passes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Passes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Passes.setHorizontalHeaderItem(3, item)
        self.gridLayout_13.addWidget(self.table_Passes, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.box_Site = QtWidgets.QGroupBox(self.tab_Passes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_Site.sizePolicy().hasHeightForWidth())
        self.box_Site.setSizePolicy(sizePolicy)
        self.box_Site.setObjectName("box_Site")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.box_Site)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Height = QtWidgets.QLabel(self.box_Site)
        self.label_Height.setObjectName("label_Height")
        self.gridLayout_4.addWidget(self.label_Height, 2, 0, 1, 1)
        self.label_Lat = QtWidgets.QLabel(self.box_Site)
        self.label_Lat.setObjectName("label_Lat")
        self.gridLayout_4.addWidget(self.label_Lat, 0, 0, 1, 1)
        self.value_Height = QtWidgets.QLineEdit(self.box_Site)
        self.value_Height.setObjectName("value_Height")
        self.gridLayout_4.addWidget(self.value_Height, 2, 1, 1, 1)
        self.value_Lon = QtWidgets.QLineEdit(self.box_Site)
        self.value_Lon.setObjectName("value_Lon")
        self.gridLayout_4.addWidget(self.value_Lon, 1, 1, 1, 1)
        self.label_Lon = QtWidgets.QLabel(self.box_Site)
        self.label_Lon.setObjectName("label_Lon")
        self.gridLayout_4.addWidget(self.label_Lon, 1, 0, 1, 1)
        self.value_Lat = QtWidgets.QLineEdit(self.box_Site)
        self.value_Lat.setObjectName("value_Lat")
        self.gridLayout_4.addWidget(self.value_Lat, 0, 1, 1, 1)
        self.button_latlon_auto = QtWidgets.QPushButton(self.box_Site)
        self.button_latlon_auto.setObjectName("button_latlon_auto")
        self.gridLayout_4.addWidget(self.button_latlon_auto, 3, 0, 1, 2)
        self.horizontalLayout_3.addWidget(self.box_Site)
        self.box_Time = QtWidgets.QGroupBox(self.tab_Passes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_Time.sizePolicy().hasHeightForWidth())
        self.box_Time.setSizePolicy(sizePolicy)
        self.box_Time.setObjectName("box_Time")
        self.gridLayout = QtWidgets.QGridLayout(self.box_Time)
        self.gridLayout.setObjectName("gridLayout")
        self.date_Start = QtWidgets.QDateTimeEdit(self.box_Time)
        self.date_Start.setObjectName("date_Start")
        self.gridLayout.addWidget(self.date_Start, 0, 1, 1, 1)
        self.label_StartTime = QtWidgets.QLabel(self.box_Time)
        self.label_StartTime.setObjectName("label_StartTime")
        self.gridLayout.addWidget(self.label_StartTime, 0, 0, 1, 1)
        self.date_Stop = QtWidgets.QDateTimeEdit(self.box_Time)
        self.date_Stop.setObjectName("date_Stop")
        self.gridLayout.addWidget(self.date_Stop, 1, 1, 1, 1)
        self.label_StopTime = QtWidgets.QLabel(self.box_Time)
        self.label_StopTime.setObjectName("label_StopTime")
        self.gridLayout.addWidget(self.label_StopTime, 1, 0, 1, 1)
        self.label_Resolution = QtWidgets.QLabel(self.box_Time)
        self.label_Resolution.setObjectName("label_Resolution")
        self.gridLayout.addWidget(self.label_Resolution, 2, 0, 1, 1)
        self.value_Resolution = QtWidgets.QDoubleSpinBox(self.box_Time)
        self.value_Resolution.setObjectName("value_Resolution")
        self.gridLayout.addWidget(self.value_Resolution, 2, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.box_Time)
        self.box_Process = QtWidgets.QGroupBox(self.tab_Passes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_Process.sizePolicy().hasHeightForWidth())
        self.box_Process.setSizePolicy(sizePolicy)
        self.box_Process.setObjectName("box_Process")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.box_Process)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.button_Process = QtWidgets.QPushButton(self.box_Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Process.sizePolicy().hasHeightForWidth())
        self.button_Process.setSizePolicy(sizePolicy)
        self.button_Process.setObjectName("button_Process")
        self.gridLayout_10.addWidget(self.button_Process, 3, 0, 1, 1)
        self.label_Status = QtWidgets.QLabel(self.box_Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Status.sizePolicy().hasHeightForWidth())
        self.label_Status.setSizePolicy(sizePolicy)
        self.label_Status.setObjectName("label_Status")
        self.gridLayout_10.addWidget(self.label_Status, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Degrees = QtWidgets.QLabel(self.box_Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Degrees.sizePolicy().hasHeightForWidth())
        self.label_Degrees.setSizePolicy(sizePolicy)
        self.label_Degrees.setObjectName("label_Degrees")
        self.horizontalLayout_4.addWidget(self.label_Degrees)
        self.value_Degrees = QtWidgets.QDoubleSpinBox(self.box_Process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_Degrees.sizePolicy().hasHeightForWidth())
        self.value_Degrees.setSizePolicy(sizePolicy)
        self.value_Degrees.setObjectName("value_Degrees")
        self.horizontalLayout_4.addWidget(self.value_Degrees)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.box_Process)
        self.gridLayout_13.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_Passes)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 2, 0, 1, 1)
        self.tabs_Calculator.addTab(self.tab_Passes, "")
        self.tab_Graph = QtWidgets.QWidget()
        self.tab_Graph.setObjectName("tab_Graph")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_Graph)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.layout_Graph = QtWidgets.QGridLayout()
        self.layout_Graph.setObjectName("layout_Graph")
        self.gridLayout_14.addLayout(self.layout_Graph, 0, 0, 1, 1)
        self.tabs_Calculator.addTab(self.tab_Graph, "")
        self.gridLayout_7.addWidget(self.tabs_Calculator, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.group_SatCalc, 0, 0, 1, 1)
        self.group_SatQueue = QtWidgets.QGroupBox(self.group_Satellites)
        self.group_SatQueue.setObjectName("group_SatQueue")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.group_SatQueue)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_Waiting = QtWidgets.QTableWidget(self.group_SatQueue)
        self.table_Waiting.setObjectName("table_Waiting")
        self.table_Waiting.setColumnCount(3)
        self.table_Waiting.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Waiting.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Waiting.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Waiting.setHorizontalHeaderItem(2, item)
        self.gridLayout_3.addWidget(self.table_Waiting, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.group_SatQueue)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.group_SatQueue, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.group_Satellites, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabs_Calculator.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_Telescope.setTitle(_translate("MainWindow", "Telescope Mount Status"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Axis 1"))
        self.label_a1_enabled.setText(_translate("MainWindow", "Enabled?"))
        self.label_a1_rms.setText(_translate("MainWindow", "RMS error"))
        self.label_a1_dist.setText(_translate("MainWindow", "dist. to target"))
        self.label_a1_servo.setText(_translate("MainWindow", "servo error"))
        self.label_a1_position.setText(_translate("MainWindow", "position"))
        self.box_MountStatus.setTitle(_translate("MainWindow", "Pointing"))
        self.label_alt_status.setText(_translate("MainWindow", "Alt"))
        self.label_ra_status.setText(_translate("MainWindow", "RA"))
        self.label_az_status.setText(_translate("MainWindow", "Az"))
        self.label_dec_status.setText(_translate("MainWindow", "Dec"))
        self.option_j2000_status.setText(_translate("MainWindow", "RA/Dec J2000?"))
        self.groupBox.setTitle(_translate("MainWindow", "Axis 0"))
        self.label_a0_enabled.setText(_translate("MainWindow", "Enabled?"))
        self.label_a0_rms.setText(_translate("MainWindow", "RMS error"))
        self.label_a0_dist.setText(_translate("MainWindow", "dist. to target"))
        self.label_a0_servo.setText(_translate("MainWindow", "servo error"))
        self.label_a0_position.setText(_translate("MainWindow", "position"))
        self.box_MountSite.setTitle(_translate("MainWindow", "Site"))
        self.label_telescope_lat.setText(_translate("MainWindow", "Latitude"))
        self.label_telescope_lon.setText(_translate("MainWindow", "Longitude"))
        self.label_telescope_height.setText(_translate("MainWindow", "Height"))
        self.label_lst.setText(_translate("MainWindow", "LST"))
        self.label_ip.setText(_translate("MainWindow", "Mount control IP"))
        self.label_port.setText(_translate("MainWindow", "port"))
        self.option_ip_local.setText(_translate("MainWindow", "localhost"))
        self.button_Connect.setText(_translate("MainWindow", "Connect to mount"))
        self.value_Connected.setText(_translate("MainWindow", "Not connected."))
        self.label_Geometry.setText(_translate("MainWindow", "Mount geometry:"))
        self.value_Geometry.setText(_translate("MainWindow", "something"))
        self.label_MoveStatus.setText(_translate("MainWindow", "Move status:"))
        self.value_MoveStatus.setText(_translate("MainWindow", "Not moving"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Direct Telescope Control"))
        self.lebel_alt_cmd.setText(_translate("MainWindow", "Alt"))
        self.label_az_cmd.setText(_translate("MainWindow", "Az"))
        self.button_goto_altaz.setText(_translate("MainWindow", "Go to alt/az"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_goto_altaz), _translate("MainWindow", "Alt/Az"))
        self.label_ra_cmd.setText(_translate("MainWindow", "RA"))
        self.label_dec_cmd.setText(_translate("MainWindow", "Dec"))
        self.option_cmd_j2000.setText(_translate("MainWindow", "J2000?"))
        self.button_goto_radec.setText(_translate("MainWindow", "Go to RA/Dec"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_goto_radec), _translate("MainWindow", "RA/Dec"))
        self.groupBox_4.setTitle(_translate("MainWindow", "TLE tracking"))
        self.button_tle_track.setText(_translate("MainWindow", "Track TLE"))
        self.label_tle_cmd.setText(_translate("MainWindow", "TLE string"))
        self.option_tle_cmd_now.setText(_translate("MainWindow", "now"))
        self.label_tle_start.setText(_translate("MainWindow", "When?"))
        self.label_tle_stop.setText(_translate("MainWindow", "Until?"))
        self.option_tle_cmd_forever.setText(_translate("MainWindow", "forever"))
        self.button_cmd_home.setText(_translate("MainWindow", "Home"))
        self.button_cmd_stop.setText(_translate("MainWindow", "Stop"))
        self.button_cmd_park.setText(_translate("MainWindow", "Park"))
        self.option_park_here.setText(_translate("MainWindow", "Here?"))
        self.option_tracking.setText(_translate("MainWindow", "Tracking"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Raw commands"))
        self.button_cmd_raw.setText(_translate("MainWindow", "PushButton"))
        self.group_Satellites.setTitle(_translate("MainWindow", "Satellites"))
        self.group_SatCalc.setTitle(_translate("MainWindow", "Pass Calculator"))
        self.button_LoadFile.setText(_translate("MainWindow", "Load File"))
        self.label_Filename.setText(_translate("MainWindow", "TLEs File name:"))
        self.label_Search.setText(_translate("MainWindow", "Search names:"))
        self.button_Search.setText(_translate("MainWindow", "Filter"))
        item = self.table_TLEs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Line 1"))
        item = self.table_TLEs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Line 2"))
        item = self.table_TLEs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Line 3"))
        self.label_6.setText(_translate("MainWindow", "Double click TLEs in this list to add to the direct control TLE tracking control"))
        self.tabs_Calculator.setTabText(self.tabs_Calculator.indexOf(self.tab_TLEs), _translate("MainWindow", "TLE List"))
        item = self.table_Passes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Satellite Name"))
        item = self.table_Passes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Max altitude"))
        item = self.table_Passes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time of max alt"))
        item = self.table_Passes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Az at max alt"))
        self.box_Site.setTitle(_translate("MainWindow", "Observation Co-ordinates"))
        self.label_Height.setText(_translate("MainWindow", "Height"))
        self.label_Lat.setText(_translate("MainWindow", "Lat"))
        self.label_Lon.setText(_translate("MainWindow", "Lon"))
        self.button_latlon_auto.setText(_translate("MainWindow", "Read from mount"))
        self.box_Time.setTitle(_translate("MainWindow", "Search parameters"))
        self.label_StartTime.setText(_translate("MainWindow", "Start Time"))
        self.label_StopTime.setText(_translate("MainWindow", "Stop Time"))
        self.label_Resolution.setText(_translate("MainWindow", "Resolution (mins)"))
        self.box_Process.setTitle(_translate("MainWindow", "Processing"))
        self.button_Process.setText(_translate("MainWindow", "Find Passes"))
        self.label_Status.setText(_translate("MainWindow", "Status: Inactive"))
        self.label_Degrees.setText(_translate("MainWindow", "Filter Alt (°)"))
        self.label_2.setText(_translate("MainWindow", "Double click passes in this list to add to the tracking queue. The telescope will track the pass when it starts."))
        self.tabs_Calculator.setTabText(self.tabs_Calculator.indexOf(self.tab_Passes), _translate("MainWindow", "Passes"))
        self.tabs_Calculator.setTabText(self.tabs_Calculator.indexOf(self.tab_Graph), _translate("MainWindow", "Graph"))
        self.group_SatQueue.setTitle(_translate("MainWindow", "Tracker Queue"))
        item = self.table_Waiting.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Satelite Name"))
        item = self.table_Waiting.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Track Start"))
        item = self.table_Waiting.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Track End"))
        self.label_3.setText(_translate("MainWindow", "Double click waiting list items to remove them from the waiting list (and cancel the tracking request)."))

